apiVersion: apps/v1
kind: Deployment
metadata:
  name: mproduits-service-app
  labels:
    app: mproduits-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : mproduits-service-app
  template:
    metadata:
      labels:
        app: mproduits-service-app
    spec:
      containers:
      - name: mproduits-service-app
        image: abdelghxni/mproduits:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name:  mproduits-service-svc
spec:
  selector:
    app:  mproduits-service-app
  ports:
    - port:  80
      targetPort:  9001
